
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
		#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"


/* event handler declarations */
void view1_button_onclicked(uib_view1_view_context*, Evas_Object*, void*);
void view1_pic_onclicked(uib_view1_view_context*, Evas_Object*, void*);

uib_view_context* uib_view_view1_create(Evas_Object* parent, void* create_callback_param) {
	uib_view1_view_context* vc = calloc(1, sizeof(uib_view1_view_context));
	vc->parent = parent;
	vc->view_name = "view1";
	vc->indicator_state = ELM_WIN_INDICATOR_SHOW;
	vc->is_user_view = false;
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	if (!vc->grid1) {
		vc->grid1= elm_grid_add(parent);
		vc->root_container = vc->grid1;
	}
	uib_views_get_instance()->set_targeted_view((uib_view_context*)vc);

	//bind event handler
	evas_object_smart_callback_add(vc->button_showhide, "clicked", (Evas_Smart_Cb)view1_button_onclicked, vc);
	evas_object_smart_callback_add(vc->pic, "clicked", (Evas_Smart_Cb)view1_pic_onclicked, vc);


	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);

	return (uib_view_context*)vc;
}
void uib_view1_config_CIRCLE_360x360_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_view1_view_context* vc = (uib_view1_view_context*)uib_app_manager->find_view_context("view1");
	if(!vc) {
		return;
	}
	if(vc->grid1) {
		elm_grid_clear(vc->grid1, EINA_FALSE);
		evas_object_size_hint_align_set(vc->grid1, -1.0, -1.0);		evas_object_size_hint_weight_set(vc->grid1, 1.0, 1.0);		elm_grid_size_set(vc->grid1, 1000, 1000);
		if (!vc->button_showhide) {
			vc->button_showhide = elm_button_add(vc->grid1);
		}
		if (vc->button_showhide) {
			evas_object_size_hint_align_set(vc->button_showhide, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->button_showhide, 1.0, 1.0);			elm_object_text_set(vc->button_showhide,_UIB_LOCALE("Show raw"));
			elm_object_style_set(vc->button_showhide,"bottom");
			evas_object_show(vc->button_showhide);
		}
		if (!vc->pic) {
			vc->pic = elm_image_add(vc->grid1);
		}
		if(vc->pic) {
			char *resource_path = NULL;
			uib_util_rm_get_resource_path(APP_RESOURCE_TYPE_IMAGE, "food_01_cooked.png", &resource_path);
			elm_image_file_set(vc->pic, resource_path, NULL);
			if(resource_path) {
				free(resource_path);
			}
			elm_image_smooth_set(vc->pic, EINA_TRUE);
			elm_image_no_scale_set(vc->pic, EINA_FALSE);
			elm_image_resizable_set(vc->pic, EINA_TRUE, EINA_TRUE);
			elm_image_aspect_fixed_set(vc->pic, EINA_FALSE);
			elm_image_fill_outside_set(vc->pic, EINA_FALSE);
			elm_image_editable_set(vc->pic, EINA_FALSE);
			evas_object_size_hint_align_set(vc->pic, -1.0, -1.0);
			evas_object_size_hint_weight_set(vc->pic, 1.0, 1.0);
			evas_object_show(vc->pic);
		}
		if (!vc->label) {
			vc->label = elm_label_add(vc->grid1);
		}
		if(vc->label) {
			evas_object_size_hint_align_set(vc->label, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->label, 1.0, 1.0);			elm_object_text_set(vc->label,_UIB_LOCALE("<p align=center>Hamburger</p>"));
			elm_label_line_wrap_set(vc->label, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->label,0);
			elm_label_ellipsis_set(vc->label, EINA_TRUE);
			evas_object_show(vc->label);
		}
		elm_grid_pack(vc->grid1, vc->button_showhide, 317, 753, 364, 250);		elm_grid_pack(vc->grid1, vc->pic, 219, 42, 553, 553);		elm_grid_pack(vc->grid1, vc->label, 65, 598, 872, 142);		evas_object_show(vc->grid1);
	}
}

