/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "uib_views.h"
#include "uib_views_inc.h"

#include <stdio.h>

// TODO: Move to control context?
int current_meal = 1;
int showing_raw = 0;
char buffer[512];
int MAX_MEAL = 7;

char* labels[] = {
		"Hamburger", "Cow",
		"Nuggets", "Rooster",
		"Sushi", "Fish",
		"Schnitzel", "Pig",
		"Egg", "Hen",
		"Dogs", "Cardboard",
		"Kiwi", "Kiwi"
};

typedef struct _uib_view1_control_context {
 /* add your variables here */
} uib_view1_control_context;

void switch_button_label(Evas_Object* button) {
	snprintf(buffer, sizeof(buffer), "Show %s", showing_raw ? "cooked" : "raw");
	elm_object_text_set(button, buffer);
}

void flip_state () {
	showing_raw = !showing_raw;
}

void change_label(Evas_Object* label) {
	snprintf(buffer, sizeof(buffer), "<p align=center>%s</p>", labels[((current_meal-1)<<1) + showing_raw]);
	elm_object_text_set(label, buffer);
}

void change_picture(Evas_Object* pic) {
	char *resource_path = NULL;
	snprintf(buffer, sizeof(buffer), "food_%02d_%s.png", current_meal, showing_raw ? "raw" : "cooked");
	uib_util_rm_get_resource_path(APP_RESOURCE_TYPE_IMAGE, buffer, &resource_path);
	elm_image_file_set(pic, resource_path, NULL);
	if(resource_path) {
		free(resource_path);
	}
}

void redraw_all(uib_view1_view_context *vc) {
	switch_button_label(vc->button_showhide);
	change_label(vc->label);
	change_picture(vc->pic);
}

void view1_button_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	flip_state();
	redraw_all(vc);
}

void view1_pic_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	++current_meal;
	if(MAX_MEAL+1 == current_meal) {
		current_meal = 1;
	}
	showing_raw = 0;
	redraw_all(vc);
}

